apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-dokumentinnsending
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 6
    max: 6
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka_pool }}
  gcp:
    sqlInstances:
      - cascadingDelete: true
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: dokumentinnsending
        diskAutoresize: true
        diskSize: {{ db_size }}
        diskType: SSD
        highAvailability: true
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        name: dp-dokumentinnsending
        pointInTimeRecovery: true
        retainedBackups: 14
        tier: {{ db_tier }}
        type: POSTGRES_14